---
- name: Configure backup server
  hosts: backup
  become: true
  tasks:
    - name: Update
      ansible.builtin.apt:
        update_cache: true
    - name: Install borgbackup
      ansible.builtin.apt:
        name: borgbackup
        state: latest
    - name: Create user borg
      ansible.builtin.user:
        name: borg
    - name: User ssh setup
      ansible.builtin.file:
        path: /home/borg/.ssh
        mode: '700'
        owner: borg
        group: borg
        state: directory
#    - name: Server keys setup
#      ansible.builtin.file:
#        path: /home/borg/.ssh/authorized_keys
#        mode: '600'
#        owner: borg
#        group: borg
#        state: touch
    - name: Format backup disk
      community.general.filesystem:
        dev: /dev/sdc
        fstype: xfs
    - name: Mount backup disk
      ansible.posix.mount:
        path: /var/backup
        state: mounted
        src: /dev/sdc
        fstype: xfs
    - name: Make backup path
      ansible.builtin.file:
        path: /var/backup
        owner: borg
        group: borg
        state: directory
    - name: Install public key
      ansible.builtin.copy:
        force: true
        remote_src: true
        src: /home/vagrant/.ssh/authorized_keys
        dest: /home/borg/.ssh/authorized_keys
        owner: borg
        group: borg
        mode: '600'


